import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import { AppProvider } from '@/core/providers';
import { Box, Heading, Flex } from '@chakra-ui/react';
import { ReactNode } from 'react';
import './styles/global.css';

const font = Nunito({ subsets: ['cyrillic', 'latin'] });

export const metadata: Metadata = {
  title: 'ArtWave',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ru">
      <body className={font.className}>
        <AppProvider>
          <Flex alignItems={'center'} justifyContent={'center'} bg={'bg.primary'} height={'60px'} width={'100vw'}>
            <Heading color={'primary.green'} fontSize={'22px'} fontWeight={'600'}>
              ArtWave
            </Heading>
          </Flex>
          <Box>{children}</Box>
          <Flex height={'300px'} />
        </AppProvider>
      </body>
    </html>
  );
}
